general.live_config_reload = true

# ENV
[env]
    term = "xterm-256color"

# WINDOW
[window]
    #opacity = 0.85
    opacity = 1.0
    padding = { x = 10 }

# CURSOR
[cursor]
    blink_timeout = 0

# SELECTION
[selection]
    save_to_clipboard = true

# COLOR
[colors.primary]
    background = "#000000"  # Black background
    foreground = "#ffffff"  # White text

[colors.cursor]
    text = "#000000" # text's color when cursor being placed at it
    cursor = "#ffffff"

# FONT
[font]
    size = 13

[font.normal]
    family = "Hack Nerd Font"

[font.bold]
    family = "Hack Nerd Font"

[font.bold_italic]
    family = "Hack Nerd Font"

[font.italic]
    family = "Hack Nerd Font"
