general.live_config_reload = true

# env
[env]
    term = "xterm-256color"

# window
[window]
    opacity = 1.0

# color
[colors.primary]
    background = "#000000"  # Black background
    foreground = "#ffffff"  # White text

[colors.cursor]
    text = "#000000"
    cursor = "#ffffff"

# font
[font]
    size = 12.5

[font.normal]
    family = "FiraCode Nerd Font"

[font.bold]
    family = "FiraCode Nerd Font"

[font.bold_italic]
    family = "FiraCode Nerd Font"

[font.italic]
    family = "FiraCode Nerd Font"
