require("config.remote_plugins_manager")
require("config.options")
require("config.linting")
require("config.lsp")
require("config.buffer_switcher")
--require("plugins.local.switcher.plugin.switcher")
