# ===== Reload ===== 
#Implicit prefix -> "Ctrl + b"
unbind r
bind r source-file ~/.tmux.conf

# ===== Pane navigation (vim-style) ===== 
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# ===== Split panes ===== 
unbind '"'
unbind %
bind | split-window -h
bind - split-window -v

# ===== True Colors ===== 
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"


# ===== Mouse ===== 
set -g mouse on

# ===== GitHub Dark pallete ===== 
bg="#0d1117"
fg="#c9d1d9"
gray="#6e7681"
blue="#58a6ff"
green="#3fb950"
yellow="#d29922"
red="#ff7b72"
magenta="#bc8cff"
cyan="#39c5cf"

# ===== Status Bar ===== 
set -g status on
set -g status-position bottom
set -g status-interval 5
set -g status-justify left
set -g status-style "fg=$fg,bg=$bg"

set -g window-status-separator "#[fg=$fg,bg=$bg,bold]|"
set -g window-status-format "#[fg=$blue,bg=$bg,italics] #I:#W "
set -g window-status-current-format "#[fg=$bg,bg=$blue,bold] #I:#W "

set -g status-left ""
set -g status-right ""
